#!/usr/bin/env node
// scripts/fetch-llama.mjs - stages the pinned llama.cpp Windows/Vulkan build. Owner: W1-07-llm-local, run once by W2-04.
//
// Contract (ARCH section 9 / build-plan section 7 `W1-07-llm-local`):
//   - downloads the PINNED llama.cpp release zip named in `vendor/llama.pin.json`, verifies the STREAMED sha256 BEFORE
//     unpacking, and unpacks only the EXPLICIT allow-list of ARCH section 9 into `vendor/llama/win-x64-vulkan`
//     (never a `*.dll` glob);
//   - writes the llama.cpp MIT text from the pinned tag into `resources/licenses/llama.cpp-MIT.txt` - ONLY that file.
//     `[repair-packaging-blocker]` It used to write `resources/licenses/THIRD_PARTY_NOTICES.txt`, which belongs to
//     W2-04-packaging and is generated by `scripts/smoke-packaged.notices.mjs` from eight sources (bridge, llama.cpp,
//     LLVM OpenMP, VC++ CRT, calendar MCP, models, Electron, ~142 npm packages). Running this script therefore
//     TRUNCATED the release notices and the correct build result depended on the order of two scripts. Now the two
//     files are disjoint: this script owns `llama.cpp-MIT.txt`, the notices generator reads it and owns
//     `THIRD_PARTY_NOTICES.txt`, and either script may run first, alone, or twice.
//   - copies `msvcp140.dll`, `vcruntime140.dll`, `vcruntime140_1.dll` from `$env:VC_REDIST_CRT_DIR` when the user set it,
//     verifying each against the sha256 pins in `vendor/llama.pin.json`; prints a loud warning and continues when unset
//     (never searches the disk). A file whose pin is `null` (UNPINNED) is REFUSED, never staged: an unverified binary
//     must not reach the installer. `node scripts/fetch-llama.mjs --pin-crt` records the hashes of the folder the
//     staging machine actually owns, and is the only way those nulls are ever filled.
//   - writes the resulting file list to `vendor/llama/MANIFEST.txt`.
//   - [signing-fix] checks every staged file against the COMMITTED per-file pins `files.fileSha256` of
//     `vendor/llama.pin.json` before writing anything; `node scripts/fetch-llama.mjs --pin-files` (downloads the pinned
//     zip) is the only way that map is filled. scripts/sign-windows.mjs signs a llama file only when it matches it.
// The downloaded binaries are NEVER executed - not by this script, not by the tests.
// `fetch` is injectable so the unit tests run with no network. No new npm dependency: the zip is read with node:zlib.
import { createHash } from 'node:crypto';
import { inflateRawSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import fsp from 'node:fs/promises';
import path from 'node:path';

export const OWNER = 'W1-07-llm-local';
export const PIN_PATH = 'vendor/llama.pin.json';
/**
 * The ONLY licence file this script writes. `resources/licenses/THIRD_PARTY_NOTICES.txt` is owned and generated by
 * `scripts/smoke-packaged.notices.mjs` (W2-04-packaging) and must never be overwritten from here.
 */
export const LLAMA_MIT_PATH = 'resources/licenses/llama.cpp-MIT.txt';
export const MANIFEST_NAME = 'MANIFEST.txt';

// ---------------------------------------------------------------------------------------------------------------------
// allow-list
// ---------------------------------------------------------------------------------------------------------------------
/** `files.exact` matches the whole base name; `files.prefix` covers the CPUID-dispatched ggml-cpu-* set. Never `*.dll`. */
export function isAllowedFile(name, allow) {
  const base = name.split('/').pop() ?? name;
  if (allow.exact.includes(base)) return true;
  return allow.prefix.some((p) => base.startsWith(p) && base.toLowerCase().endsWith('.dll'));
}

// ---------------------------------------------------------------------------------------------------------------------
// minimal ZIP reader (stored + deflate; the official asset is a flat zip well under 4 GiB, so no zip64 handling)
// ---------------------------------------------------------------------------------------------------------------------
export function readZipEntries(buffer) {
  const buf = Buffer.isBuffer(buffer) ? buffer : Buffer.from(buffer);
  let eocd = -1;
  for (let i = buf.length - 22; i >= 0; i -= 1) {
    if (buf.readUInt32LE(i) === 0x06054b50) {
      eocd = i;
      break;
    }
  }
  if (eocd === -1) throw new Error('fetch-llama: not a zip archive (no end-of-central-directory record)');
  const count = buf.readUInt16LE(eocd + 10);
  let at = buf.readUInt32LE(eocd + 16);
  const entries = [];
  for (let i = 0; i < count; i += 1) {
    if (buf.readUInt32LE(at) !== 0x02014b50) throw new Error('fetch-llama: corrupt central directory');
    const method = buf.readUInt16LE(at + 10);
    const compressedSize = buf.readUInt32LE(at + 20);
    const uncompressedSize = buf.readUInt32LE(at + 24);
    const nameLen = buf.readUInt16LE(at + 28);
    const extraLen = buf.readUInt16LE(at + 30);
    const commentLen = buf.readUInt16LE(at + 32);
    const localOffset = buf.readUInt32LE(at + 42);
    const name = buf.toString('utf8', at + 46, at + 46 + nameLen);
    entries.push({ name, method, compressedSize, uncompressedSize, localOffset });
    at += 46 + nameLen + extraLen + commentLen;
  }
  return entries.map((e) => ({
    name: e.name,
    read: () => {
      if (buf.readUInt32LE(e.localOffset) !== 0x04034b50)
        throw new Error(`fetch-llama: corrupt local header for ${e.name}`);
      const nameLen = buf.readUInt16LE(e.localOffset + 26);
      const extraLen = buf.readUInt16LE(e.localOffset + 28);
      const start = e.localOffset + 30 + nameLen + extraLen;
      const raw = buf.subarray(start, start + e.compressedSize);
      if (e.method === 0) return Buffer.from(raw);
      if (e.method === 8) return inflateRawSync(raw);
      throw new Error(`fetch-llama: unsupported compression method ${String(e.method)} for ${e.name}`);
    },
    uncompressedSize: e.uncompressedSize,
    isDirectory: e.name.endsWith('/'),
  }));
}

// ---------------------------------------------------------------------------------------------------------------------
// download + verify
// ---------------------------------------------------------------------------------------------------------------------
export async function fetchVerified({ fetch, url, sha256, size }) {
  if (!url.startsWith('https://')) throw new Error('fetch-llama: only https:// downloads are allowed');
  // Fail closed BEFORE the network call: an absent pin must never degrade into "download and trust".
  if (typeof sha256 !== 'string' || !/^[0-9a-f]{64}$/.test(sha256)) {
    throw new Error(`fetch-llama: the asset is UNPINNED in ${PIN_PATH} (llama.sha256) - refusing to download`);
  }
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) throw new Error(`fetch-llama: HTTP ${String(res.status)} for the pinned asset`);
  const bytes = Buffer.from(await res.arrayBuffer());
  if (typeof size === 'number' && bytes.length !== size) {
    throw new Error(`fetch-llama: size mismatch (expected ${String(size)}, got ${String(bytes.length)})`);
  }
  const digest = createHash('sha256').update(bytes).digest('hex');
  if (digest !== sha256) throw new Error('fetch-llama: sha256 mismatch - refusing to unpack');
  return bytes;
}

export async function fetchText({ fetch, url }) {
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) throw new Error(`fetch-llama: HTTP ${String(res.status)} for ${url}`);
  return await res.text();
}

// ---------------------------------------------------------------------------------------------------------------------
// VC++ CRT staging
// ---------------------------------------------------------------------------------------------------------------------
export function crtPlan({ env, pin }) {
  const dir = env[pin.vcRedistCrt.sourceEnvVar];
  const names = Object.keys(pin.vcRedistCrt.files).filter((n) => !n.startsWith('_'));
  if (typeof dir !== 'string' || dir === '') return { dir: null, names, warning: 'VC_REDIST_CRT_DIR_UNSET' };
  return { dir, names, warning: null };
}

export async function stageCrt({ plan, pin, fs, targetDir, log }) {
  if (plan.dir === null) {
    log(
      '\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n' +
        '!! VC_REDIST_CRT_DIR is not set - the MSVC CRT is NOT staged app-locally.\n' +
        '!! On a PC without the VC++ 2015-2022 x64 Redistributable llama-server.exe\n' +
        '!! dies at load (0xC0000135) and the app shows LLM_VCREDIST_MISSING.\n' +
        '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n',
    );
    return [];
  }
  const staged = [];
  for (const name of plan.names) {
    const source = path.join(plan.dir, name);
    const bytes = await fs.readFile(source);
    const digest = createHash('sha256').update(bytes).digest('hex');
    const pinned = pin.vcRedistCrt.files[name];
    if (pinned === null || pinned === undefined) {
      // Do NOT warn-and-continue: that is how an unverified DLL ends up inside a signed installer.
      throw new Error(
        `fetch-llama: ${name} is UNPINNED in ${PIN_PATH} - refusing to stage an unverified binary. ` +
          `Run \`node scripts/fetch-llama.mjs --pin-crt\` on the machine that owns the Microsoft.VC143.CRT folder ` +
          `(its sha256 is ${digest}), review the recorded hashes, then re-run.`,
      );
    }
    if (typeof pinned !== 'string' || !/^[0-9a-f]{64}$/.test(pinned)) {
      throw new Error(`fetch-llama: ${name} has a malformed sha256 pin in ${PIN_PATH}`);
    }
    if (pinned !== digest) throw new Error(`fetch-llama: ${name} sha256 does not match the pin in ${PIN_PATH}`);
    await fs.writeFile(path.join(targetDir, name), bytes);
    staged.push(name);
  }
  return staged;
}

/** Hashes the three CRT files in `$VC_REDIST_CRT_DIR` without copying or executing anything. */
export async function crtDigests({ plan, fs }) {
  if (plan.dir === null)
    throw new Error(`fetch-llama: --pin-crt needs $VC_REDIST_CRT_DIR to point at a Microsoft.VC143.CRT folder`);
  const out = {};
  for (const name of plan.names) {
    const bytes = await fs.readFile(path.join(plan.dir, name));
    out[name] = createHash('sha256').update(bytes).digest('hex');
  }
  return out;
}

/**
 * `--pin-crt`: records the sha256 of the CRT files the staging machine actually owns into `vendor/llama.pin.json`.
 * Edits the three values in place (a regex per name) so the file's comments and formatting survive untouched.
 */
export function applyCrtPins(source, digests) {
  let out = source;
  for (const [name, digest] of Object.entries(digests)) {
    const re = new RegExp(`("${name.replace(/\./g, '\\.')}"\\s*:\\s*)(null|"[0-9a-f]{64}")`);
    if (!re.test(out)) throw new Error(`fetch-llama: ${name} has no slot in ${PIN_PATH}`);
    out = out.replace(re, `$1"${digest}"`);
  }
  return out;
}

export async function pinCrt(io = {}) {
  const fs = io.fs ?? fsp;
  const env = io.env ?? process.env;
  const log = io.log ?? ((m) => process.stdout.write(`${m}\n`));
  const root = io.root ?? path.resolve(fileURLToPath(new URL('..', import.meta.url)));

  const pinPath = path.join(root, PIN_PATH);
  const source = await fs.readFile(pinPath, 'utf8');
  const pin = JSON.parse(source);
  const digests = await crtDigests({ plan: crtPlan({ env, pin }), fs });
  const updated = applyCrtPins(source, digests);
  await fs.writeFile(pinPath, updated, 'utf8');
  for (const [name, digest] of Object.entries(digests)) log(`pinned ${name} = ${digest}`);
  log(
    `fetch-llama: recorded ${String(Object.keys(digests).length)} CRT pins in ${PIN_PATH} - commit this change deliberately.`,
  );
  return digests;
}

// ---------------------------------------------------------------------------------------------------------------------
// [signing-fix, signing-review MAJOR 3] COMMITTED per-file pins: `files.fileSha256` in the pin file maps every
// allow-listed name of the PINNED zip to its sha256. vendor/ is gitignored, so without these the only reference for a
// staged file was the staged file itself; scripts/sign-windows.mjs signs a llama / whisper file only when it matches.
// `--pin-files` is the only way the map is ever filled: it downloads the pinned zip, verifies it, hashes in memory.
// ---------------------------------------------------------------------------------------------------------------------
const sha256Hex = (bytes) => createHash('sha256').update(bytes).digest('hex');
const sortedObject = (o) =>
  Object.fromEntries(
    Object.keys(o)
      .sort()
      .map((k) => [k, o[k]]),
  );

/** The allow-listed entries of a (verified) zip as [{ name, bytes }]; `nameOf` maps an entry name (null = skip). */
export function allowedZipFiles(zip, pin, nameOf = (n) => n.split('/').pop() ?? n) {
  const out = [];
  for (const entry of readZipEntries(zip)) {
    if (entry.isDirectory) continue;
    const name = nameOf(entry.name);
    if (name === null || !isAllowedFile(name, { exact: pin.files.exact, prefix: pin.files.prefix })) continue;
    out.push({ name, bytes: entry.read() });
  }
  return out;
}

/** name -> sha256 of every allow-listed entry of the zip, sorted by name. Pure, in memory. */
export function zipFileDigests(zip, pin, nameOf) {
  return sortedObject(Object.fromEntries(allowedZipFiles(zip, pin, nameOf).map((f) => [f.name, sha256Hex(f.bytes)])));
}

/**
 * Checks the files about to be staged against `pin.files.fileSha256`. null / absent => UNPINNED: warns (the fetch
 * still works; signed builds refuse) and returns false. A map => every staged file must be pinned and match, and every
 * pinned name must be staged; anything else throws BEFORE a single file is written.
 */
export function checkFilePins(digests, pin, { pinPath, script, log }) {
  const map = pin.files.fileSha256;
  if (map === null || map === undefined) {
    log(
      `fetch: WARNING ${pinPath} files.fileSha256 is UNPINNED - the staged files are only as trustworthy as vendor/; ` +
        `signed builds refuse them. Run \`node ${script} --pin-files\`, review and commit the hashes.`,
    );
    return false;
  }
  if (typeof map !== 'object') throw new Error(`fetch: ${pinPath} files.fileSha256 is malformed`);
  for (const [name, digest] of Object.entries(digests)) {
    const want = map[name];
    if (typeof want !== 'string' || !/^[0-9a-f]{64}$/.test(want)) {
      throw new Error(`fetch: ${name} has no per-file pin in ${pinPath} files.fileSha256 - refusing to stage it`);
    }
    if (want !== digest) throw new Error(`fetch: ${name} does not match its per-file pin in ${pinPath}`);
  }
  for (const name of Object.keys(map)) {
    if (!name.startsWith('_') && !Object.hasOwn(digests, name)) {
      throw new Error(`fetch: ${name} is pinned in ${pinPath} files.fileSha256 but is not in the asset`);
    }
  }
  return true;
}

/**
 * Writes `files.fileSha256` into the pin file TEXT: replaces the `"fileSha256": null | {...}` slot in place, so the
 * comments and the rest of the formatting survive (the slot sits at 4 spaces inside "files").
 */
export function applyFilePins(source, digests) {
  const re = /("fileSha256"\s*:\s*)(null|\{[^{}]*\})/;
  if (!re.test(source)) throw new Error('fetch: the pin file has no files.fileSha256 slot');
  const body = JSON.stringify(sortedObject(digests), null, 2).replace(/\n/g, '\n    ');
  return source.replace(re, (_m, key) => `${key}${body}`);
}

/**
 * `--pin-files`: downloads the PINNED zip (refused unless size + sha256 match the pin), hashes the allow-listed
 * entries in memory and records them in the pin file. Nothing is unpacked, nothing is executed.
 * @param {object} io  `{ fetch, fs, log, root }`
 * @param {{ pinPath: string, asset: string, nameOf?: (n: string) => string | null, label: string }} [what]
 */
export async function pinFiles(io = {}, what = { pinPath: PIN_PATH, asset: 'llama', label: 'fetch-llama' }) {
  const fetchFn = io.fetch ?? globalThis.fetch;
  const fs = io.fs ?? fsp;
  const log = io.log ?? ((m) => process.stdout.write(`${m}\n`));
  const root = io.root ?? path.resolve(fileURLToPath(new URL('..', import.meta.url)));
  const pinPath = path.join(root, what.pinPath);
  const source = (await fs.readFile(pinPath, 'utf8')).toString();
  const pin = JSON.parse(source);
  const a = pin[what.asset];
  const zip = await fetchVerified({ fetch: fetchFn, url: a.url, sha256: a.sha256, size: a.size });
  const digests = zipFileDigests(zip, pin, what.nameOf);
  await fs.writeFile(pinPath, applyFilePins(source, digests), 'utf8');
  for (const [name, digest] of Object.entries(digests)) log(`pinned ${name} = ${digest}`);
  log(
    `${what.label}: recorded ${String(Object.keys(digests).length)} per-file pins in ${what.pinPath} - ` +
      'commit this change deliberately.',
  );
  return digests;
}

// ---------------------------------------------------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------------------------------------------------
export async function main(io = {}) {
  const fetchFn = io.fetch ?? globalThis.fetch;
  const fs = io.fs ?? fsp;
  const env = io.env ?? process.env;
  const log = io.log ?? ((m) => process.stdout.write(`${m}\n`));
  const root = io.root ?? path.resolve(fileURLToPath(new URL('..', import.meta.url)));

  const pin = JSON.parse(await fs.readFile(path.join(root, PIN_PATH), 'utf8'));
  const targetDir = path.join(root, ...pin.llama.targetDir.split('/'));
  await fs.mkdir(targetDir, { recursive: true });

  const zip = await fetchVerified({
    fetch: fetchFn,
    url: pin.llama.url,
    sha256: pin.llama.sha256,
    size: pin.llama.size,
  });
  // [signing-fix] every file is checked against the committed per-file pins BEFORE anything is written
  const files = allowedZipFiles(zip, pin);
  checkFilePins(Object.fromEntries(files.map((f) => [f.name, sha256Hex(f.bytes)])), pin, {
    pinPath: PIN_PATH,
    script: 'scripts/fetch-llama.mjs',
    log,
  });
  const written = [];
  for (const { name, bytes } of files) {
    await fs.writeFile(path.join(targetDir, name), bytes);
    written.push(name);
  }
  if (!written.includes('llama-server.exe'))
    throw new Error('fetch-llama: llama-server.exe is not in the pinned asset');

  // The verbatim MIT text of the PINNED tag, and nothing else: `scripts/smoke-packaged.notices.mjs` reads this file
  // and builds `THIRD_PARTY_NOTICES.txt` (llama.cpp section 2, VC++ CRT section 4) from it. Writing the notices file
  // from here would truncate seven other sections and make the release artefact depend on which script ran last.
  const license = await fetchText({ fetch: fetchFn, url: pin.llama.licenseUrl });
  const llamaMitPath = path.join(root, ...LLAMA_MIT_PATH.split('/'));
  await fs.mkdir(path.dirname(llamaMitPath), { recursive: true });
  // Verbatim, with no added header: this file IS the licence copy the MIT terms require, and the notices generator
  // reproduces it under a section heading that already names the tag and the release URL.
  await fs.writeFile(llamaMitPath, `${license.trim()}\n`, 'utf8');

  const staged = await stageCrt({ plan: crtPlan({ env, pin }), pin, fs, targetDir, log });
  const all = [...written, ...staged].sort();
  await fs.writeFile(path.join(root, ...pin.llama.targetDir.split('/'), MANIFEST_NAME), `${all.join('\n')}\n`, 'utf8');
  log(`fetch-llama: staged ${String(all.length)} files into ${pin.llama.targetDir}`);
  return { files: all, targetDir };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const run = process.argv.includes('--pin-crt')
    ? pinCrt
    : process.argv.includes('--pin-files')
      ? () => pinFiles()
      : main;
  run().catch((err) => {
    process.stderr.write(`fetch-llama: ${err instanceof Error ? err.message : String(err)}\n`);
    process.exit(1);
  });
}
