#!/usr/bin/env node
// scripts/fetch-whisper.mjs - stages the pinned whisper.cpp Windows CPU build (ARCH-v2 B18 / 12). Owner: V2-W1-07-media-voice; run by
// V2-W2-04-packaging only (D-017) - a builder writes and tests it with an injected fetch and NEVER runs it.
//
// Contract (clone of fetch-llama.mjs):
//   - downloads the PINNED `whisper-bin-x64.zip` of tag b5130 named in `vendor/whisper.pin.json`, verifies size + sha256 BEFORE
//     unpacking (an absent pin refuses to download at all);
//   - strips the zip's `Release/` prefix and unpacks ONLY the explicit allow-list (whisper-cli.exe, whisper.dll, ggml.dll,
//     ggml-base.dll, ggml-cpu-*.dll) into `vendor/whisper/win-x64-cpu` - its OWN folder: ggml b5130 must never mix with llama's b10964;
//     any entry in another sub-folder is refused;
//   - copies the three VC++ CRT DLLs from $VC_REDIST_CRT_DIR when set, each verified against its pin (fetch-llama's rules: an
//     UNPINNED CRT file is refused, an unset variable only warns);
//   - writes the whisper.cpp MIT text of the pinned tag into `resources/licenses/whisper.cpp-MIT.txt` ONLY (the notices file
//     THIRD_PARTY_NOTICES.txt is generated by scripts/smoke-packaged.notices.mjs, which reads this file - the same split as llama);
//   - writes the staged file list to `vendor/whisper/MANIFEST.txt` and, [V2-W2-04], the sha256 of every staged file to
//     `vendor/whisper/SHA256SUMS` (`<hex> *<name>`, the bridge's format) - the packaged smoke (T2 11 check 7) hashes every
//     file of `<resources>\whisper` against it (the zip itself is verified by its pin before anything is unpacked).
//   - [signing-fix] checks every staged file against the COMMITTED per-file pins `files.fileSha256` of
//     `vendor/whisper.pin.json` before writing anything (`--pin-files` fills them from the pinned zip).
// The downloaded binaries are NEVER executed - not by this script, not by the tests (T8).
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import fsp from 'node:fs/promises';
import path from 'node:path';
import {
  allowedZipFiles,
  checkFilePins,
  crtPlan,
  fetchText,
  fetchVerified,
  pinFiles as pinFilesOf,
  stageCrt,
} from './fetch-llama.mjs';

export const OWNER = 'V2-W1-07-media-voice';
export const PIN_PATH = 'vendor/whisper.pin.json';
export const WHISPER_MIT_PATH = 'resources/licenses/whisper.cpp-MIT.txt';
export const MANIFEST_PATH = 'vendor/whisper/MANIFEST.txt';
/** [V2-W2-04] per-file sha256 of the staged set (T2 11 check 7). */
export const SUMS_PATH = 'vendor/whisper/SHA256SUMS';

/** `<hex> *<name>` lines, sorted by name - parsed by hash-bridge.mjs parseSums. */
export function sumsText(digests) {
  return `${Object.keys(digests)
    .sort()
    .map((name) => `${digests[name]} *${name}`)
    .join('\n')}\n`;
}
/** The only sub-folder the official asset uses; stripped. Anything nested deeper, or in another folder, is refused. */
export const STRIP_PREFIX = 'Release/';

/** `Release/whisper-cli.exe` -> `whisper-cli.exe`; a bare name stays; any other folder => null (refused). */
export function stripReleasePrefix(name) {
  const n = name.replace(/\\/g, '/');
  const rest = n.startsWith(STRIP_PREFIX) ? n.slice(STRIP_PREFIX.length) : n;
  if (rest === '' || rest.includes('/') || rest === '..' || rest === '.') return null;
  return rest;
}

export async function main(io = {}) {
  const fetchFn = io.fetch ?? globalThis.fetch;
  const fs = io.fs ?? fsp;
  const env = io.env ?? process.env;
  const log = io.log ?? ((m) => process.stdout.write(`${m}\n`));
  const root = io.root ?? path.resolve(fileURLToPath(new URL('..', import.meta.url)));

  const pin = JSON.parse(await fs.readFile(path.join(root, PIN_PATH), 'utf8'));
  const targetDir = path.join(root, ...pin.whisper.targetDir.split('/'));
  await fs.mkdir(targetDir, { recursive: true });

  const zip = await fetchVerified({
    fetch: fetchFn,
    url: pin.whisper.url,
    sha256: pin.whisper.sha256,
    size: pin.whisper.size,
  });
  // [signing-fix] every file is checked against the committed per-file pins BEFORE anything is written
  const files = allowedZipFiles(zip, pin, stripReleasePrefix);
  checkFilePins(
    Object.fromEntries(files.map((f) => [f.name, createHash('sha256').update(f.bytes).digest('hex')])),
    pin,
    { pinPath: PIN_PATH, script: 'scripts/fetch-whisper.mjs', log },
  );
  const written = [];
  for (const { name, bytes } of files) {
    await fs.writeFile(path.join(targetDir, name), bytes);
    written.push(name);
  }
  for (const required of pin.files.required) {
    if (!written.includes(required)) throw new Error(`fetch-whisper: ${required} is not in the pinned asset`);
  }

  const license = await fetchText({ fetch: fetchFn, url: pin.whisper.licenseUrl });
  const mitPath = path.join(root, ...WHISPER_MIT_PATH.split('/'));
  await fs.mkdir(path.dirname(mitPath), { recursive: true });
  await fs.writeFile(mitPath, `${license.trim()}\n`, 'utf8');

  const staged = await stageCrt({ plan: crtPlan({ env, pin }), pin, fs, targetDir, log });
  const all = [...written, ...staged].sort();
  const manifestPath = path.join(root, ...MANIFEST_PATH.split('/'));
  await fs.mkdir(path.dirname(manifestPath), { recursive: true });
  await fs.writeFile(manifestPath, `${all.join('\n')}\n`, 'utf8');
  const digests = {};
  for (const name of all) {
    digests[name] = createHash('sha256')
      .update(await fs.readFile(path.join(targetDir, name)))
      .digest('hex');
  }
  await fs.writeFile(path.join(root, ...SUMS_PATH.split('/')), sumsText(digests), 'utf8');
  log(`fetch-whisper: staged ${String(all.length)} files into ${pin.whisper.targetDir}`);
  return { files: all, targetDir, digests };
}

/**
 * [signing-fix] `--pin-files`: records `files.fileSha256` (Release/ stripped) from the verified, PINNED zip in
 * vendor/whisper.pin.json. vendor/whisper/SHA256SUMS is gitignored and written by the same fetch, so it can never be
 * the signing reference; scripts/sign-windows.mjs signs a whisper file only when it matches these committed pins.
 */
export function pinFiles(io = {}) {
  return pinFilesOf(io, { pinPath: PIN_PATH, asset: 'whisper', nameOf: stripReleasePrefix, label: 'fetch-whisper' });
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  (process.argv.includes('--pin-files') ? pinFiles() : main()).catch((err) => {
    process.stderr.write(`fetch-whisper: ${err instanceof Error ? err.message : String(err)}\n`);
    process.exit(1);
  });
}
